### s3 Folder create api

POST http://localhost:3000/api/folders HTTP/1.1
Content-Type: application/json

{
  "folderPath": "lse-test-data",
  "folderName": "lse-test-data",
  "folderType": "S3",
  "readOnly": true
}

### local Folder create api

POST http://localhost:3000/api/folders HTTP/1.1
Content-Type: application/json

{
  "folderPath": "/home/deepak/Projects/private-nx-repo/dist/apps/study-content-lib",
  "folderName": "lse-test-data",
  "folderType": "FILE_SYSTEM",
  "readOnly": true
}

### Folder findAll api

GET http://localhost:3000/api/folders HTTP/1.1
Content-Type: application/json


### Folder scan folder api

GET http://localhost:3000/api/folders/scan/1 HTTP/1.1
Content-Type: application/json